# Generated by Django 4.2.1 on 2023-05-19 05:29

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('qualification_upto', models.IntegerField(blank=True, choices=[(1, 'SEE'), (2, '+2'), (3, 'DIPLOMA'), (4, 'BACHELORS'), (5, 'POST GRADUATE DIPLOMA'), (6, 'MASTERS')], help_text='Qualification done by student upto now.', null=True)),
                ('qualification_for', models.IntegerField(blank=True, choices=[(1, 'SEE'), (2, '+2'), (3, 'DIPLOMA'), (4, 'BACHELORS'), (5, 'POST GRADUATE DIPLOMA'), (6, 'MASTERS')], help_text='Qualification for which student want to go abroad.', null=True)),
                ('country_for', apps.core.models.ModifiedArrayField(base_field=models.CharField(blank=True, choices=[(1, 'UNITED STATES OF AMERICA'), (2, 'AUSTRAILIA'), (3, 'UNITED KINGDOM'), (4, 'CANADA'), (5, 'EUROPE'), (6, 'NEW ZEALAND'), (7, 'DUBAI'), (8, 'JAPAN'), (9, 'KOREA'), (10, 'INDIA'), (11, 'BANGLADESH')], max_length=100, null=True), blank=True, null=True, size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.IntegerField(blank=True, choices=[(1, 'FACEBOOK'), (2, 'INSTAGRAM'), (3, 'OTHERS')], null=True)),
                ('link', models.CharField(max_length=255)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.applicant')),
            ],
        ),
    ]
