# Generated by Django 4.2.1 on 2023-05-19 06:09

import apps.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='country_for',
            field=apps.core.models.ModifiedArrayField(base_field=models.CharField(blank=True, choices=[(1, 'USA'), (2, 'AUSTRAILIA'), (3, 'UNITED KINGDOM'), (4, 'CANADA'), (5, 'EUROPE'), (6, 'NEW ZEALAND'), (7, 'DUBAI'), (8, 'JAPAN'), (9, 'KOREA'), (10, 'INDIA'), (11, 'BANGLADESH')], max_length=100, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='qualification_for',
            field=models.IntegerField(blank=True, choices=[(1, 'SEE'), (2, '+2'), (3, 'DIPLOMA'), (4, 'BACHELORS'), (5, 'POST GRADUATE DIPLOMA'), (6, 'MASTERS'), (7, 'B. Nursing'), (8, 'PCL Nursing')], help_text='Qualification for which student want to go abroad.', null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='qualification_upto',
            field=models.IntegerField(blank=True, choices=[(1, 'SEE'), (2, '+2'), (3, 'DIPLOMA'), (4, 'BACHELORS'), (5, 'POST GRADUATE DIPLOMA'), (6, 'MASTERS'), (7, 'B. Nursing'), (8, 'PCL Nursing')], help_text='Qualification done by student upto now.', null=True),
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, choices=[(1, 'SEE'), (2, '+2'), (3, 'DIPLOMA'), (4, 'BACHELORS'), (5, 'POST GRADUATE DIPLOMA'), (6, 'MASTERS'), (7, 'B. Nursing'), (8, 'PCL Nursing')], null=True)),
                ('grade', models.CharField(max_length=255)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.applicant')),
            ],
        ),
    ]
