# Generated by Django 4.2.1 on 2023-05-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_applicant_country_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='answer',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
