# Generated by Django 4.2.1 on 2023-05-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_query_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='question',
            field=models.TextField(max_length=255),
        ),
    ]
